#include<stdio.h>
int main()
{
    int n,d,res=0,once=0,a,max=0,count=0;
    scanf("%d%d",&n,&d);
    while(n)
    {
        a=n%d;
        n=n/d;
        if(a==0)
        {
            once=1;
            res++;
            count=res;
        }
        else
        {
            if(count>max)
            {
                max=count;
            }
            res=0;
        }
    }
    if(once==0)
    {
        printf("-1");
    }
    else
    {
        printf("%d",count);
    }
}